### ISSUE TITLE
Nice theme, but I encountered a problem "block in setup': You have already activated rouge 1.11.1, but your Gemfile requires rouge 2.0.7. Prepending `bundle "

### ISSUE THREAD

**Issue by nalakawula** [kuoa/julia#1]
I want to run your great theme, but got error. Could you help me?
here the log:
```shell
[sumarsono@mesin-fedora julia]$ jekyll serve
/home/sumarsono/.gem/ruby/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:40:in `block in setup': You have already activated rouge 1.11.1, but your Gemfile requires rouge 2.0.7. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
        from /home/sumarsono/.gem/ruby/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:25:in `map'
        from /home/sumarsono/.gem/ruby/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:25:in `setup'
        from /home/sumarsono/.gem/ruby/2.3.0/gems/bundler-1.14.6/lib/bundler.rb:100:in `setup'
        from /home/sumarsono/.gem/ruby/2.3.0/gems/jekyll-3.4.3/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
        from /home/sumarsono/.gem/ruby/2.3.0/gems/jekyll-3.4.3/exe/jekyll:9:in `<top (required)>'
        from /home/sumarsono/bin/jekyll:22:in `load'
        from /home/sumarsono/bin/jekyll:22:in `<main>'
```
thanks

**Comment by kuoa** [comment]
Hello!
As the log file indicates you have rouge 1.11.1 installed in your system but the theme uses version 2.0.7
One way to fix this is to run `bundle exec jekyll serve` .

"bundle exec is a Bundler command to execute a script in the context of the current bundle (the one from your directory's Gemfile)", this will install the new gem for you and it should fix the problem.

**Comment by nalakawula** [comment]
thanks
